[package]
name = "cribbage_scorer"
version = "0.1.0"
authors = ["Connor Szczepaniak <cszczepaniak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"

[dev-dependencies]
claim = "0.5"
